config/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from cmms.views import (
    CostCentreViewSet,
    LocationViewSet,
    ContractorViewSet,
    InvoiceViewSet,
    UserProfileViewSet,
    DeviceViewSet,
    MakeViewSet,
    GenreViewSet,
    TicketViewSet,
    ServiceViewSet,
    HospitalViewSet,
    MileageViewSet
)

# Router dla API v1
router = DefaultRouter()
router.register(r'v1/cost_centre', CostCentreViewSet)
router.register(r'v1/location', LocationViewSet)
router.register(r'v1/contractor', ContractorViewSet)
router.register(r'v1/invoice', InvoiceViewSet)
router.register(r'v1/userprofile', UserProfileViewSet)
router.register(r'v1/device', DeviceViewSet)
router.register(r'v1/make', MakeViewSet)
router.register(r'v1/genre', GenreViewSet)
router.register(r'v1/ticket', TicketViewSet)
router.register(r'v1/service', ServiceViewSet)
router.register(r'v1/hospital', HospitalViewSet)
router.register(r'v1/mileage', MileageViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(router.urls)),
    path('crm/', include('crm.urls')),
]

crm/urls.py
from django.urls import path

from . import views

app_name = 'crm'

urlpatterns = [
    path('hospitals', views.HospitalListView.as_view(), name='hospitals'),
    path('fetch-company-data/', views.fetch_company_data, name='fetch_company_data'),
]

crm/models.py
from django.db import models
import cmms
from django.conf import settings
from django.contrib.auth.models import AbstractUser

import utils
from utils.models import DiffedHistoricalRecords

CHOICES_INVOICE_STATUS = (
    (1, 'Projekt'),
    (2, 'Zapisana'),
    (3, 'Zaakceptowana'),
    (4, u'Zaksięgowana'),
)

CHOICES_VAT = (
    (1, '8%'),
    (2, '23%'),
    (3, 'zw'),
)

User = settings.AUTH_USER_MODEL


class UserProfile(AbstractUser):
    stamp = models.ImageField(upload_to='stamps/', null=True, blank=True, verbose_name=u'Pieczątka')
    signature = models.ImageField(upload_to='signatures/', null=True, blank=True, verbose_name=u'Podpis')
    phone = models.CharField("Telefon", max_length=100, blank=True, null=True)

    class Meta:
        ordering = ['username', 'first_name', ]

    def __str__(self):
        # check if name is provided
        try:
            name = self.get_full_name()
        except:
            name = self.username

        if not name:
            name = self.username

        return name


# Create your models here.
class Hospital(models.Model):
    name = models.CharField(max_length=255, verbose_name=u'Nazwa')
    street = models.CharField(max_length=255, verbose_name=u'Ulica')
    street_number = models.CharField(max_length=255, verbose_name=u'Nr posesji')
    postal_code = models.CharField(max_length=255, verbose_name=u'Kod pocztowy')
    city = models.CharField(max_length=255, verbose_name=u'Miejscowość')
    logo = models.ImageField(upload_to='logo/', null=True, blank=True, verbose_name=u'Logo')
    NIP = models.BigIntegerField(verbose_name=u'NIP')
    REGON = models.BigIntegerField(verbose_name=u'REGON')
    KRS = models.BigIntegerField(verbose_name=u'KRS')
    telephone = models.CharField(max_length=255, verbose_name=u'Telefon', null=True, blank=True)
    fax = models.CharField(max_length=255, verbose_name=u'Fax', null=True, blank=True)
    email = models.CharField(max_length=255, verbose_name=u'E-mail')

    class Meta:
        app_label = 'crm'
        verbose_name = u'Placówka medyczna'
        verbose_name_plural = u'Placówki medyczne'

    def __str__(self):
        return self.name


class Location(models.Model):
    history = DiffedHistoricalRecords()
    staff_pks = models.TextField(max_length=4096, blank=True, null=True, verbose_name=u'Personel')

    name = models.CharField(max_length=255, verbose_name=u'Nazwa')
    description = models.TextField(max_length=4096, null=True, blank=True, verbose_name=u'Opis')
    street = models.CharField(max_length=255, verbose_name=u'Ulica')
    street_number = models.CharField(max_length=255, verbose_name=u'Nr posesji')
    postal_code = models.CharField(max_length=255, verbose_name=u'Kod pocztowy')
    city = models.CharField(max_length=255, verbose_name=u'Miejscowość')
    person = models.ForeignKey(User, verbose_name=u'Osoba', related_name='person', on_delete=models.CASCADE)
    staff = models.ManyToManyField(User, verbose_name=u'Personel', related_name='staff', blank=True)
    telephone = models.CharField(max_length=255, verbose_name=u'Telefon', null=True, blank=True)
    fax = models.CharField(max_length=255, verbose_name=u'Fax', null=True, blank=True)
    email = models.CharField(max_length=255, verbose_name=u'E-mail')

    custom_m2m_history = {
        "staff_pks": ["crm.models.UserProfile", "staff"]
    }

    class Meta:
        verbose_name = u'Lokalizacja'
        verbose_name_plural = u'Lokalizacje'
        ordering = ['name', ]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        # try to get original object
        if self.pk:
            original = Location.objects.get(pk=self.pk)
        else:
            original = None

        # save object
        super(Location, self).save(*args, **kwargs)

        person_changed = True

        devices = cmms.models.Device.objects.filter(location=self)
        devices_ids = [i.pk for i in devices]

        # compare changes, just to see if there is any reason in updating permissions
        if original:
            if self.person == original.person:
                person_changed = False

        # set permission if person_responsible_changed
        if person_changed:
            # setup_permissions.delay(person, list of devices to reset, list of devices to set permissions)
            if original and original.person:
                if not original.person.has_perm("cmms.view_all_devices"):
                    utils.tasks.setup_permissions.delay(original.person.pk, devices_ids, devices_ids)
            if self.person:
                utils.tasks.setup_permissions.delay(self.person.pk, devices_ids, devices_ids)


class CostCentre(models.Model):
    symbol = models.CharField(max_length=255, verbose_name=u'Symbol')
    name = models.CharField(max_length=255, verbose_name=u'Nazwa')
    description = models.TextField(max_length=4096, null=True, blank=True, verbose_name=u'Opis')

    class Meta:
        verbose_name = u'Centrum kosztowze'
        verbose_name_plural = u'Centra kosztowe'

    def __str__(self):
        return self.name


class Contractor(models.Model):
    history = DiffedHistoricalRecords()
    staff_pks = models.TextField(max_length=4096, blank=True, null=True, verbose_name=u'Pracownicy')

    name = models.CharField(max_length=255, verbose_name=u'Nazwa')
    NIP = models.BigIntegerField(verbose_name=u'NIP')
    street = models.CharField(max_length=255, verbose_name=u'Ulica')
    street_number = models.CharField(max_length=255, verbose_name=u'Nr posesji')
    postal_code = models.CharField(max_length=255, verbose_name=u'Kod pocztowy')
    city = models.CharField(max_length=255, verbose_name=u'Miejscowość')
    email = models.EmailField(blank=True, null=True)
    staff = models.ManyToManyField(User, verbose_name=u'Pracownicy', related_name='contractor_staff', blank=True)

    custom_m2m_history = {
        "staff_pks": ["crm.models.UserProfile", "staff"]
    }

    class Meta:
        verbose_name = u'Kontrahent'
        verbose_name_plural = u'Kontrahenci'

    def __unicode__(self):
        return self.name


class Invoice(models.Model):
    history = DiffedHistoricalRecords()
    service_pks = models.TextField(max_length=4096, blank=True, null=True, verbose_name=u'Zlecenia')

    id = models.AutoField(primary_key=True, auto_created=True)
    number = models.CharField(max_length=100, verbose_name=u'Numer', unique=True)
    name = models.CharField(max_length=255, verbose_name=u'Nazwa')
    description = models.TextField(max_length=4096, null=True, blank=True, verbose_name=u'Opis')
    scan = models.FileField(upload_to='invoices/', null=True, blank=True, verbose_name=u'Skan')
    net_value = models.DecimalField(verbose_name=u'Wartość netto', max_digits=9, decimal_places=2)
    gross_value = models.DecimalField(verbose_name=u'Wartość brutto', max_digits=9, decimal_places=2)
    contractor = models.CharField(verbose_name=u'Kontrahent', max_length=255, blank=True, null=True)
    hospital = models.CharField(verbose_name=u'Szpital', max_length=255, blank=True, null=True)
    created_by = models.ForeignKey('UserProfile', null=True, blank=True, on_delete=models.CASCADE)
    status = models.IntegerField(choices=CHOICES_INVOICE_STATUS, verbose_name=u'status', null=True, blank=True)
    service = models.ManyToManyField('cmms.Service', verbose_name='Zlecenia')
    date = models.DateField(verbose_name=u'Data faktury')
    payment_date = models.DateField(verbose_name=u'Data płatności', blank=True, null=True)
    created_at = models.DateField(verbose_name=u'Data dodania', auto_now_add=True)
    posting_date = models.DateField(verbose_name=u'Data księgowania', blank=True, null=True)

    custom_m2m_history = {
        "service_pks": ["crm.models.Service", "service"]
    }

    def has_costs_breakdown(self):
        return CostBreakdown.objects.filter(invoice_id=self.id).count() > 0

    def get_services(self):
        invoice_services = InvoiceService.objects.filter(invoice=self)
        services_id = [row.service_id for row in invoice_services]

        return cmms.models.Service.objects.filter(id__in=services_id)

    def is_accepted(self):
        return self.status == 3

    class Meta:
        verbose_name = u'Faktura'
        verbose_name_plural = u'Faktury'

    def __str__(self):
        return "%f" % self.gross_value

    def save(self, *args, **kwargs):
        if not self.status:
            self.status = 1

        super(Invoice, self).save(*args, **kwargs)


class InvoiceItem(models.Model):
    invoice = models.ForeignKey('Invoice', verbose_name=u'Faktura', on_delete=models.CASCADE)
    name = models.CharField(max_length=1024, verbose_name=u'Nazwa')
    symbol = models.CharField(max_length=128, verbose_name=u'Symbol')
    net_price = models.DecimalField(verbose_name=u'Cena netto', max_digits=9, decimal_places=2)
    amount = models.IntegerField(verbose_name=u'Ilość')
    net_cost = models.DecimalField(verbose_name=u'Koszt netto', max_digits=9, decimal_places=2)
    gross_cost = models.DecimalField(verbose_name=u'Koszt brutto', max_digits=9, decimal_places=2)
    vat = models.IntegerField(choices=CHOICES_VAT)

    class Meta:
        verbose_name = u'Pozycja faktury'
        verbose_name_plural = u'Pozycje faktury'

    def __str__(self):
        return self.name


class InvoiceService(models.Model):
    invoice = models.ForeignKey('Invoice', on_delete=models.CASCADE)
    service = models.ForeignKey('cmms.Service', on_delete=models.CASCADE)


class CostBreakdown(models.Model):
    invoice = models.ForeignKey('Invoice', verbose_name=u'Faktura', on_delete=models.CASCADE)
    device_name = models.CharField(verbose_name=u'Urządzenie', max_length=255)
    device_id = models.IntegerField(verbose_name=u'ID urządzenia')
    device_manufacturer = models.CharField(verbose_name=u'Producent urządzenia', max_length=255)
    device_model = models.CharField(verbose_name=u'Model urządzenia', max_length=255)

templates/inspections/inspection_headlines.html
{% block content %}
    <form id='inspections-form' action="/pdf-generate-directly/" method="post">{% csrf_token %}
        <input type="hidden" id='id_inspection_pdf_model' name="model">
        <input type="hidden" id='id_inspection_pdf_ids' name="ids">
        <input type="hidden" id='id_inspection_pdf_titles' name="titles">
    </form>
    <h1 style="text-align: center">Plan przeglądów/konserwacji</h1>
    <table id="inspections-table" style="width:100%;" class="display" >
        <thead>
            <tr>
                <th width=1%><input type="checkbox" id="selall" value=""></th>
                <th>
                    ID przeglądu
                </th>
                <th>
                    ID urządzenia
                </th>
                <th>
                    Nazwa urz.
                </th>
                <th>
                    Producent
                </th>
                <th>
                    Model
                </th>
                <th>
                    Nr seryjny
                </th>
                <th>
                    Nr inw.
                </th>
                <th>
                    Lokalizacja
                </th>
                <th>
                    ID zgłoszenia
                </th>
                <th>
                    Rodzaj czynności cyklicznej
                </th>
                <th>
                    Planowana data wykonania
                </th>
                <th>
                    Data wykonania
                </th>
                <th>
                    Wykonawca
                </th>
                 <th>
                    Firma wykonująca
                </th>
                <th>
                    Uwagi
                </th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>

{% endblock %}

templates/inspections/inspections.html
{% extends 'base.html' %}

{% block content %}
	<div class="yui-g">
        {% if add_ticket %}
        <script>
            blink = true;
        </script>
        {% endif %}
        {% if new_device %}
        <script>
            new_device = true;
        </script>
        {% endif %}
        {% if device_id %}
        <script>
            device_id = {{ device_id }};
        </script>
        {% endif %}
        {% if devices_group_id %}
        <script>
            devices_group_id = {{ devices_group_id }};
        </script>
        {% endif %}
        {% include 'inspections/inspection_headlines.html' %}
	</div>
 <script>
load_inspections();
 </script>
{% endblock %}

templates/inspections/new_inspection.html
<script type="text/javascript" src="/site_media/filter_objects.js"></script>
<script type="text/javascript" src="/site_media/jquery-ui-1.8.17.custom/js/jquery-ui-1.8.17.custom.min.js"></script>
<script>
    IS_INSPECTION_PAGE = true;
</script>

<div class="action-form">
    <h1>Nowy plan przeglądów</h1>
    <form action="{% url 'inspection-add' %}" method="POST" id="add-inspection">{% csrf_token %}
        <table>
            <tr>
                <td>
                    <table>
                        <tbody>
                            <tr>
                                <th colspan="2" style="text-align: left">Szczegóły przeglądu/konserwacji</th>
                            </tr>
                            <tr>
                                <th>{{ form.name.label }}*</th>
                                <td>
                                    {{ form.name }}
                                    <div style="color:red" class="errors error_name"></div>
                                </td>
                            </tr>
                            <tr>
                                <th>{{ form.type.label }}</th>
                                <td>
                                    {{ form.type }}
                                    <div style="color:red" class="errors error_type"></div>
                                </td>
                            </tr>
                            <tr>
                                <th>{{ form.priority.label }}</th>
                                <td>
                                    {{ form.priority }}
                                    <div style="color:red" class="errors error_priority"></div>
                                </td>
                            </tr>
                            <tr>
                                <th>{{ form.duration_time.label }}</th>
                                <td>
                                    {{ form.duration_time }}
                                    {{ form.duration_period }}
                                    <div style="color:red" class="errors error_duration_time"></div>
                                </td>
                            </tr>
                            <tr>
                                <th>{{ form.description.label }}</th>
                                <td>
                                    {{ form.description }}
                                    <div style="color:red" class="errors error_description"></div>
                                </td>
                            </tr>
                            <tr>
                                <th colspan="2" style="text-align: left">Powiązane urządzenia</th>
                            </tr>
                            <tr>
                                <td colspan="2">
                                    {% if devices %}
                                        <a class='filter-objects' data-objects_name="device">Zmień powiązane urządzenia</a>
                                        <div>Wybrane obiekty:</div>
                                        <table id="related_devices">
                                            <tr>
                                                <td>Id</td>
                                                <td>Nazwa</td>
                                                <td>Producent</td>
                                                <td>Model</td>
                                                <td>Nr seryjny</td>
                                                <td>Nr inwentarzowy</td>
                                                <td>Lokalizacja</td>
                                            </tr>
                                            {% for current_related_object in devices %}
                                                <input type="hidden" name="device" value="{{ current_related_object.pk }}">
                                                <tr class="current_related_objects_device">
                                                    <td id="{{ current_related_object.pk }}">{{ current_related_object.pk }}.</td>
                                                    <td>
                                                        <a href="{{ current_related_object.get_absolute_url }}">
                                                            {{ current_related_object }}</a>
                                                    </td>
                                                    <td>{{ current_related_object.make }}</td>
                                                    <td>{{ current_related_object.model }}</td>
                                                    <td>{{ current_related_object.serial_number }}</td>
                                                    <td>{{ current_related_object.inventory_number }}</td>
                                                    <td>{{ current_related_object.location }}</td>
                                                </tr>
                                            {% endfor %}
                                        </table>
                                    {% else %}
                                        <a class='filter-objects' data-objects_name="device">Dodaj powiązane urządzenia</a>
                                        <table id="inspection_related_devices" style="margin-left: 100px">
                                            <tr><td><p>Brak powiązanych urządzeń</p></td></tr>
                                            <tr><td><div style="color:red" class="errors error_related_devices"></div></td></tr>
                                        </table>
                                    {% endif %}
                                </td>
                            </tr>
                            <tr>
                                <th colspan="2" style="text-align: left">Harmonogram wykonania</th>
                            </tr>
                            <tr>
                                <td colspan="2">Utwórz {{ form.count_planned_events }} <span style="color:red" class="errors error_count_planned_events"></span> planowanych zdarzeń
                                    co {{ form.cycle_value }} <span style="color:red" class="errors error_cycle_value"></span> {{ form.cycle_value_period }} zaczynając od
                                    {{ form.cycle_date_start }} <span style="color:red" class="errors error_cycle_date_start"></span> <br/>

                                    Utwórz nowe zgłoszenia: {{ form.recurring_time }} <span style="color:red" class="errors error_recurring_time"></span>
                                    {{ form.recurring_period }}
                                    przed planowanymi datami wykonania.
                                </td>
                            </tr>
                            <tr style="text-align: center">
                                <td colspan="4">
                                    <div class="button-inspection-middle create_events">Utwórz</div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <table>
                        <tbody>
                            <tr class="planned_ticket_to_change"></tr>
                            <tr>
                                <th colspan="2">Części</th>
                                <td colspan="2">
                                    {{ form.device_elements }}
                                    <div style="color:red" class="errors error_device_elements"></div>
                                </td>

                            </tr>
                            <tr>
                                <td colspan="3">
                                    <div class="button-inspection-save generate_tickets" style="padding: 5px">Generuj przeglądy/konserwacje"</div>
                                </td>
                                <td><div class="button-inspection-cancel">Anuluj</div></td>
                            </tr>
                        </tbody>
                    </table>
                </td>
            </tr>
        </table>
    </form>
</div>
<script>
    $(document).ready(function(){

        $("#id_count_planned_events").keyup(function(){
           var value = $(this).val();
           if(value == '1' || value == 1) {
               $("#id_cycle_value").attr("disabled", "disabled");
               $("#id_cycle_value_period").attr("disabled", "disabled");
           } else {
               $("#id_cycle_value").attr("disabled", false);
               $("#id_cycle_value_period").attr("disabled", false);
           }
        });

        $(".button-inspection-cancel").click(function(){
            location.href = "/przeglady"
        });

        $("#id_cycle_date_start").datepicker({ dateFormat: "yy-mm-dd" });

        if ( typeof(window.LAST_INSPECTION_DATA) !== 'undefined' && window.LAST_INSPECTION_DATA) {
            for (name in window.LAST_INSPECTION_DATA) {
                $("[name='"+name+"']").val(window.LAST_INSPECTION_DATA[name]);
            }
        }

        $(".create_events").click(function(){
            $("[class^='errors']").text("");
            var name = $("#id_name").val();
            var count_planned_events = $("#id_count_planned_events").val();
            var cycle_value = $("#id_cycle_value").val();
            var cycle_value_period = $("#id_cycle_value_period").val();
            var cycle_date_start = $("#id_cycle_date_start").val();
            var recurring_time = $("#id_recurring_time").val();
            var recurring_period = $("#id_recurring_period").val();

            var devices = "";
            $("[name='device']").each(function(){
                devices = devices + $(this).val() + ",";
            });
            devices = devices.slice(0, devices.length-1)

            $.get("/utworz-zdarzenia?name="+name+"&count_planned_events="+count_planned_events+
                    "&cycle_value="+cycle_value+"&cycle_value_period="+cycle_value_period+
                    "&cycle_date_start="+cycle_date_start+"&recurring_time="+recurring_time+
                    "&recurring_period="+recurring_period+"&devices="+devices, function(data) {
                $(".planned_event").remove();

                if (data['planned_events_table']) {
                    $(".planned_ticket_to_change").after(data['planned_events_table']);
                } else {
                    for (var field in data['errors']){
                        var field_name = field;
                        var error = data['errors'][field];
                        $(".error_"+field_name).text(error);
                    }
                }
            });
        });

        $(".generate_tickets").click(function(){

            $("[class^='errors']").text("");

            var data_to_send = $("form").serialize();
            var url = $("#add-inspection").attr("action");

            var devices = "";
            $("[name='device']").each(function(){
                devices = devices + $(this).val() + ",";
            });
            devices = devices.slice(0, devices.length-1)

            if (devices == "") {
                alert("Wybierz co najmniej jedno urządzenie!")
            } else {
                $.fancybox("<div style='height:100px;background-color:grey;padding-top:57px;padding-left:10px;padding-right:10px;color:white;'>Trwa generowanie przeglądów.<br/>Proszę czekać...</div>")
            }
            $.post(url, data_to_send, function(data){

                if (data["save"]) {
                    location.href = "/przeglady"
                } else {
                    for (var field in data){
                        var field_name = field;
                        var error = data[field];
                        $(".error_"+field_name).text(error);
                    }

                }
            });
        })


    });

</script>

templates/inspections/planned_tickets.html
<tr class="planned_event">
    <th colspan="4" style="text-align: left">Lista wygenerowanych zdarzeń:</th>
</tr>
<tr class="planned_event">
    <th style="text-align: left">Lp.</th>
    <th style="text-align: left">Nazwa</th>
    <th style="text-align: left">Planowana data wykonania</th>
    <th style="text-align: left">Data utworzenia zgłoszenia</th>
</tr>
{% for event in events %}
    <tr class="planned_event">
        <td>{{ forloop.counter }}.</td>
        <td>{{ event.name }}</td>
        <td>{{ event.date_planned|date:"d M Y" }}</td>
        <td>{{ event.date_ticket|date:"d M Y" }}</td>
    </tr>
{% endfor %}